export enum UserRole {
  STUDENT = "STUDENT",
  LECTURER = "LECTURER",
  ADMIN_STAFF = "ADMIN_STAFF",
  DEPT_HEAD = "DEPT_HEAD",
  INSTITUTION_MGMT = "INSTITUTION_MGMT",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum ComplaintStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  AWAITING_INFORMATION = "AWAITING_INFORMATION",
  ESCALATED = "ESCALATED",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
  REJECTED = "REJECTED",
}

export enum TicketStatus {
  OPEN = "OPEN",
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_INFO = "PENDING_INFO",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}

export enum TicketPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum TicketSeverity {
  MINOR = "MINOR",
  MODERATE = "MODERATE",
  MAJOR = "MAJOR",
  CRITICAL = "CRITICAL",
}

export enum NotificationType {
  COMPLAINT_UPDATE = "COMPLAINT_UPDATE",
  TICKET_ASSIGNED = "TICKET_ASSIGNED",
  ESCALATION = "ESCALATION",
  SYSTEM = "SYSTEM",
  ANNOUNCEMENT = "ANNOUNCEMENT",
}

export enum EscalationLevel {
  DEPARTMENT = "DEPARTMENT",
  INSTITUTION = "INSTITUTION",
  EXTERNAL = "EXTERNAL",
}
